### ISSUE TITLE
Google API modules

### ISSUE THREAD

**Issue by btsimonh** [tasmota/Berry_playground#11]
@s-hadinger recently did some great work on enabling RSA signatures.
As a result, we can now access Google cloud apis, including Google Drive.

My first attempt at some 'libraries' are here:
https://github.com/btsimonh/TasmotaBerryPLay/tree/master/googleapis

Do you want me to fork and PR?
Is this the kind of style we're looking for?

Edit: reading the discussions, looks like this could be the first subfolder in 'Modules'?

**Comment by s-hadinger** [comment]
Yes please

**Comment by dkebler** [comment]
Let me set up this folder skeleton then you can fork and add your folder under `tools`

**Comment by dkebler** [comment]
To leave a nice trail for your proposed addition I was hoping folks would first start a discussion topic for the contribution in the appropriate category and then when it all seems good make a PR in issues that can be merged.   

So now that I have have created those categories and made a new topic  #12  in discussions.   Once things are hammered you can start a new PR under issues.

So closing this now in favor of #12
